########################################################################################################################
# 1. BLACK #############################################################################################################
########################################################################################################################
[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''

    (
      /(
          \.eggs         # exclude a few common directories in the
        | \.git          # root of the project
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
        | \..*           # anything that starts with "."
      )/
      | foo.py           # also separately exclude a file named foo.py in
                         # the root of the project
    )
    '''

########################################################################################################################
# 2. PYLINT ############################################################################################################
########################################################################################################################
[tool.pylint."MESSAGES CONTROL"]
disable = [
    "line-too-long"
    ]

########################################################################################################################
# 3. MYPY ##############################################################################################################
########################################################################################################################
[mypy]
ignore_missing_imports = true

########################################################################################################################
# 4. COVERAGE ##########################################################################################################
########################################################################################################################
[tool.coverage.run]
omit = [
    # __init__.py, __about__.py
    '*__*__*',

    # tests
    '*tests*',
    ]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    'pragma: no cover',

    # Don't complain about missing debug-only code:
    'def __repr__',
    'if self\.debug',

    # Don't complain if tests don't hit defensive assertion code:
    'raise AssertionError',
    'raise NotImplementedError',

    # Don't complain if non-runnable code isn't run:
    'if 0:',
    'if __name__ == .__main__.:',
    ]
ignore_errors = true

[tool.coverage.html]
directory = 'coverage'
